name: Run Linter

on: workflow_call

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v3
      # - name: 'Setup Node.js | Node Version: 16'
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: 16
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: "deps-node-modules-${{ hashFiles('**/package-lock.json') }}"
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
