name: Run Formatter, Linter and Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  # format:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: 'Setup Node.js | Node Version: 16'
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 16
  #     - name: Cache dependencies
  #       id: cache-deps
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.npm
  #         key: "deps-node-modules-${{ hashFiles('**/package-lock.json') }}"
  #     - name: Install dependencies
  #       if: steps.cache-deps.outputs.cache-hit != 'true'
  #       run: npm ci
  #     - name: Lint code
  #       run: npm run format
  lint:
    # needs: 'format'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 'Setup Node.js | Node Version: 16'
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: "deps-node-modules-${{ hashFiles('**/package-lock.json') }}"
      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint code
        run: npm run format
  test:
    needs: 'lint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: 'Setup Node.js | Node Version: 16'
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: "deps-node-modules-${{ hashFiles('**/package-lock.json') }}"
      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint code
        run: npm run format
