name: Retrieve Secret
on: [workflow_dispatch]
jobs:
  output-secrets:
    runs-on: ubuntu-latest
    env:
      MY_SECRET: ${{ secrets.MY_SECRET }}
    steps:
      - name: Output Secret
        run: echo ${{ secrets.MY_SECRET }}
