name: Unit Tests

on: workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # node-version: [16]
        node-version: [14, 16, latest]
      # max-parallel: 1
    steps:
      - name: 'Checkout source code'
        uses: actions/checkout@v3
      - name: 'Setup Node.js | Node Version: ${{ matrix.node-version }}'
        continue-on-error: true
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run unit test
        run: npm test
  # test-1:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: 'Checkout source code'
  #       uses: actions/checkout@v3
  #     - name: Cache node_modules
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.npm
  #         key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run unit test
  #       run: npm test
  # test-2:
  #   needs: test-1
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: 'Checkout source code'
  #       uses: actions/checkout@v3
  #     - name: Cache node_modules
  #       uses: actions/cache@v3
  #       with:
  #         path: ~/.npm
  #         key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Run unit test
  #       run: npm test
