name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 16
        # node-version: [14, 16, latest]
      # max-parallel: 1
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3
      - name: "Setup Node.js | Node Version: ${{ matrix.node-version }}"
        continue-on-error: true
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }} 
          # cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run unit test
        run: npm test
  test-again:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: latest
        # node-version: [14, 16, latest]
      # max-parallel: 1
    steps:
      - name: "Checkout source code"
        uses: actions/checkout@v3
      - name: "Setup Node.js | Node Version: ${{ matrix.node-version }}"
        continue-on-error: true
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }} 
      - name: Install dependencies
        run: npm ci
      - name: Run unit test
        run: npm test

